# Change this if Fly says the app name is already taken.
app = "clinicians-semantic-search-api"
primary_region = "sea"

[build]
  dockerfile = "Dockerfile"

[env]
  ENVIRONMENT = "production"

[http_service]
  internal_port = 8000
  force_https = true
  auto_start_machines = true
  auto_stop_machines = "stop"
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "2gb"
