#!/bin/bash
echo "🎯 Therapist Search Development Scripts"
echo "======================================"
echo ""
echo "Available commands:"
echo ""
echo "Development:"
echo "  ./scripts/dev/start-local-app.sh      - Start backend with local DB"
echo "  ./scripts/dev/start-supabase.sh   - Start backend with Supabase"
echo "  ./scripts/dev/start-frontend.sh   - Start frontend only"
echo "  ./scripts/dev/start-all-local.sh  - Start full stack locally (backend and frontend)"
echo ""
echo "Database:"
echo "  ./scripts/utils/setup-db.sh local    - Setup local database"
echo "  ./scripts/utils/setup-db.sh supabase - Setup Supabase database"
echo "  ./scripts/utils/migrate-data.sh load - Load therapist data"
echo "  ./scripts/utils/migrate-data.sh clean - Clean encoding issues"
echo "  ./scripts/utils/migrate-data.sh test  - Test search functionality"
echo "  ./scripts/utils/migrate-data.sh load-supabase - Load data to Supabase"
echo ""
echo "Deployment:"
echo "  ./scripts/deploy/deploy-backend.sh  - Deploy backend to Render"
echo "  ./scripts/deploy/deploy-frontend.sh - Deploy frontend"
echo "  ./scripts/deploy/deploy-all.sh      - Deploy full stack"
echo ""
echo "Utilities:"
echo "  ./scripts/utils/check-status.sh     - Check system status"
echo "  ./scripts/utils/check-env.sh        - Check current environment"
echo ""
echo "Example: ./scripts/dev/start-local.sh"